name: "PNPM Install"
description: "Install dependencies with pnpm"

inputs:
  target:
    description: "The name of the directory where the install should run"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      env:
        NODE_VERSION: "16"
      with:
        node-version: "${{ env.NODE_VERSION }}"
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.target }}
